### ISSUE TITLE
During editing types two symbols appear

### ISSUE THREAD

**Issue by AnnaFri** [conterra/mapapps-editing-types#1]
I have experienced a confusing behaviour while editing features, which types are used for visualisation. I have a service, which contains three layers. Each of those layers has four sublayers. "House", "Ship" and "Pin" are the layers and "blue", "red", "yellow" and "green" are the sublayers. There is a field "category" for "House", etc. and a field "type" for the colors. 

While editing from a blue house to a red ship, both symbols are displayed in the map and the red ship overlays the blue house. After I saved and stopped the editing and zoomed in to make a new request call to the service, only the red ship appears in the map (which is how it is supposed to be). So, the editing itself works fine. But it is a little confusing that two symbols appear during the editing. Is there any solution for this?

**Comment by SarahLechler** [comment]
Thank you for your contribution. We entered a bug for this issue.
